title: "My Course Site"
description: "A site for course listings and details."
baseurl: ""
url: "" # Replace with your GitHub Pages URL
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
