title: "Zhenyuan Lu's Course Home Page"
description: "This is the main course page for holding all the course sites that Zhenyuan Lu is teaching."
baseurl: "/teachings"
url: "https://zhenyuanlu.com"

markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false


author:
  name: "Zhenyuan Lu"
  email: "lu.zhenyua@northeastern.edu"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
include:
  - _courses


exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

collections:
  courses:
    output: true
    permalink: /:slug/
