title: "Teachings | Zhenyuan Lu, PhD | Machine Learning & Data Science"
description: "I am a deep learning scientist and adjunct faculty passionate about teaching and sharing what I have learned with amazing students. Here, you will find resources, insights, and all the course I teach in AI/ML and data science."
baseurl: "/courses"
url: "https://zhenyuanlu.com"

markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

google_analytics_id: G-GHCNZ4G83S

icon_set: "fontawesome"  # options: lucide or fontawesome

author:
  name: "Zhenyuan Lu"
  email: "zh.lu@northeastern.edu"
  url: "https://zhenyuanlu.com/courses"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-email-protect
  
include:
  - _courses
  - "*.pdf"


exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

collections:
  courses:
    output: true
    permalink: /:slug/

sass:
  style: compressed