title: "Teachings | Zhenyuan Lu | Machine Learning & Data Science"
description: "This is the main course page for holding all the course sites that Zhenyuan Lu is teaching."
baseurl: "/courses"
url: "https://zhenyuanlu.com"

markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

author:
  name: "Zhenyuan Lu"
  email: "zh.lu@northeastern.edu"
  url: "https://zhenyuanlu.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect
  
include:
  - _courses


exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

collections:
  courses:
    output: true
    permalink: /:slug/
